[package]
name = "sludge-cicd"
version = "0.1.19"
edition = "2021"
repository = "https://github.com/SludgePhD/CICD"
description = "Personal CI/CD tool for Rust crates"
license = "MIT OR Apache-2.0"

[dev-dependencies]
expect-test = "1.5.0"
